### ISSUE TITLE
Sort by Most Recently Added (Extensions, Apps, Etc.)

### ISSUE THREAD

**Issue by PrismBoy123** [spicetify/spicetify-marketplace#466] opened 2023-03-24 05:07 UTC
There will be a drop down menu and clickable button to enable it 👍

The Marketplace will default to Most Recent whenever opened.

**Comment by theRealPadster** [comment] 2023-03-24 06:08
Duplicate of #5

**Closed by theRealPadster** 2023-03-24 06:08 UTC
