### ISSUE TITLE
Cant open marketplace on arch linux

### ISSUE THREAD

**Issue by NaufalF22** [spicetify/spicetify-marketplace#239] opened 2022-06-16 12:08 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.84.716-2
- Spicetify version:2.10.1-1
```

### 📝 Description

Cant open marketplace at arch AUR

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/63091744/174066408-dca85a6b-9c22-4549-82fa-ea975269dd09.png)

**Comment by theRealPadster** [comment] 2022-06-16 13:01
Downgrade to spicetify 2.9.9. People seem to have issues with using the latest spicetify with Spotify 1.1.84

**Comment by theRealPadster** [comment] 2022-06-16 13:02
Closing as a duplicate of #227

**Closed by theRealPadster** 2022-06-16 13:02 UTC
Labels: 🐛 bug
