### ISSUE TITLE
i cant downloand spicetify

### ISSUE THREAD

**Issue by Kowalskyi** [spicetify/spicetify-marketplace#190] opened 2022-05-17 23:49 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: idk
- Spicetify version:2.9.8
```

### 📝 Description

 iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
>> iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marketplace/master/install.ps1 | iex
DOWNLOADING    https://api.github.com/repos/spicetify/spicetify-cli/releases/latest > OK
DOWNLOADING    https://github.com/spicetify/spicetify-cli/releases/download/v2.9.8/spicetify-2.9.8-windows-x64.zip > OK
EXTRACTING     C:\Users\elmas\spicetify-cli\spicetify-2.9.8-windows-x64.zip into C:\Users\elmas\spicetify-cli > OK
REMOVING       C:\Users\elmas\spicetify-cli\spicetify-2.9.8-windows-x64.zip > OK
 > OK
Run spicetify --help to get started.

Setting up...
Downloading...
Unzipping and installing...
spicetify-marketplace was already found! Updating...
warning Config "custom_apps" unchanged: spicetify-marketplace is already in the list.
spicetify v2.9.8
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Overwriting raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc000e70000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc0001c0de0, 0x2b}, 0xc0001878d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc0001c0de0, 0x2e}, {{0x14fcff8, 0x0, 0x0}, {0xc00009a080, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc0000107e0, 0x1e}, {{0x14fcff8, 0x0, 0x0}, {0xc00009a080, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0x12cb7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b
Done! If nothing has happened, do spicetify apply

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/105757559/168930027-9a2818c5-170e-42e0-822f-cffad31be8e3.png)

**Comment by Etx4n** [comment] 2022-05-18 04:38
i have the same issue :/

**Comment by theRealPadster** [comment] 2022-05-19 16:32
1. Not related to marketplace. 
2. Dupe of https://github.com/spicetify/spicetify-cli/issues/1687

**Closed by theRealPadster** 2022-05-19 16:32 UTC
Labels: 🐛 bug
