### ISSUE TITLE
Spicetify Marketplace keeps reverting back to normal spotify

### ISSUE THREAD

**Issue by JollyFunTime** [spicetify/spicetify-marketplace#580] opened 2023-08-20 11:45 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.18.999.g9b38fc27
- Spicetify version:2.22.2
```

### 📝 Description

it keeps going back to normal spotify even though i havent unistalled it or played with any commands

### 📸 Screenshots

normal spotify gui w/o the marketplace option and themes/plugins/apps etc.

**Comment by theRealPadster** [comment] 2023-08-23 04:29
Sounds like you've got the Microsoft store version installed or something else that would prevent spicetify from persisting changes. Don't use the MS store version. Not a bug with the marketplace app, so closing.

**Closed by theRealPadster** 2023-08-23 04:29 UTC
Labels: 🐛 bug
